var group___u_s_b_d_m___group =
[
    [ "OSC, Crystal Oscillator", "group___o_s_c___group.html", "group___o_s_c___group" ],
    [ "RTC, Real Time Clock", "group___r_t_c___group.html", "group___r_t_c___group" ],
    [ "MCG, Multipurpose Clock Generator", "group___m_c_g___group.html", "group___m_c_g___group" ],
    [ "SIM, System Integration Module", "group___s_i_m___group.html", "group___s_i_m___group" ],
    [ "ADC, Analogue Input", "group___a_d_c___group.html", "group___a_d_c___group" ],
    [ "CMP, Analogue Comparator", "group___c_m_p___group.html", "group___c_m_p___group" ],
    [ "CMT, Carrier Modulator Transmitter", "group___c_m_t___group.html", "group___c_m_t___group" ],
    [ "CONTROL, Control", "group___control___group.html", "group___control___group" ],
    [ "CRC, Cyclic Redundancy Check", "group___c_r_c___group.html", "group___c_r_c___group" ],
    [ "Console, Console Interface", "group___c_o_n_s_o_l_e___group.html", "group___c_o_n_s_o_l_e___group" ],
    [ "DMA, Direct Memory Access (DMA)", "group___d_m_a___group.html", "group___d_m_a___group" ],
    [ "DMAMUX, Direct Memory Access (DMA)", "group___d_m_a_m_u_x___group.html", "group___d_m_a_m_u_x___group" ],
    [ "EWM, External Watchdog Monitor", "group___e_w_m___group.html", "group___e_w_m___group" ],
    [ "FTFL, Flash Memory Module", "group___f_t_f_l___group.html", "group___f_t_f_l___group" ],
    [ "FTM, PWM, Input capture and Output compare", "group___f_t_m___group.html", "group___f_t_m___group" ],
    [ "GPIO, Digital Input/Output", "group___g_p_i_o___group.html", "group___g_p_i_o___group" ],
    [ "I2C, Inter-Integrated-Circuit Interface", "group___i2_c___group.html", "group___i2_c___group" ],
    [ "I2S, Synchronous Audio Interface", "group___i2_s___group.html", "group___i2_s___group" ],
    [ "LLWU, Low-leakage Wake-up Unit", "group___l_l_w_u___group.html", "group___l_l_w_u___group" ],
    [ "LPTMR, Low Power Timer", "group___l_p_t_m_r___group.html", "group___l_p_t_m_r___group" ],
    [ "MCM, Miscellaneous Control Module", "group___m_c_m___group.html", "group___m_c_m___group" ],
    [ "PDB, Programmable Delay Block", "group___p_d_b___group.html", "group___p_d_b___group" ],
    [ "PIT, Programmable Interrupt Timer", "group___p_i_t___group.html", "group___p_i_t___group" ],
    [ "PMC, Power Management Controller", "group___p_m_c___group.html", "group___p_m_c___group" ],
    [ "POWER, Power", "group___power___group.html", "group___power___group" ],
    [ "RCM, Reset Control Module", "group___r_c_m___group.html", "group___r_c_m___group" ],
    [ "SMC, System Mode Controller", "group___s_m_c___group.html", "group___s_m_c___group" ],
    [ "SPI, Serial Peripheral Interface", "group___s_p_i___group.html", "group___s_p_i___group" ],
    [ "TSI, Touch Sense Interface", "group___t_s_i___group.html", "group___t_s_i___group" ],
    [ "UART, Universal Asynchronous Receiver/Transmitter", "group___u_a_r_t___group.html", "group___u_a_r_t___group" ],
    [ "USB, USB OTG Controller", "group___u_s_b___group.html", "group___u_s_b___group" ],
    [ "USBDCD, USB Device Charger Detection", "group___u_s_b_d_c_d___group.html", "group___u_s_b_d_c_d___group" ],
    [ "VREF, Voltage Reference", "group___v_r_e_f___group.html", "group___v_r_e_f___group" ],
    [ "WDOG, Watchdog Timer", "group___w_d_o_g___group.html", "group___w_d_o_g___group" ],
    [ "CheckSignal", "class_u_s_b_d_m_1_1_check_signal.html", null ],
    [ "mapAllPins", "group___u_s_b_d_m___group.html#gac1583ceab2863eb2d7f89299357fb5b6", null ],
    [ "max", "group___u_s_b_d_m___group.html#gab8dc590ea65bc6f66c08734546cd8cfa", null ],
    [ "min", "group___u_s_b_d_m___group.html#ga9f1b14a39d297580a6148e26075817f7", null ],
    [ "MAP_ALL_PINS", "group___u_s_b_d_m___group.html#ga44180eaca88ffd00a6945b630a962cbe", null ],
    [ "NoPortInfo", "group___u_s_b_d_m___group.html#gaba5a9aba19b84e827dfe5d3128d20067", null ],
    [ "PORTA_IRQS_AR", "group___u_s_b_d_m___group.html#ga01a271627b8cf03b0c9f0904aa4a143e", null ],
    [ "PortAInfo", "group___u_s_b_d_m___group.html#gabe155138b1827229a2023f35c166ab00", null ],
    [ "PORTB_IRQS_AR", "group___u_s_b_d_m___group.html#gac3b2fdc02e5ca7da6dc2f0b04df6ae0f", null ],
    [ "PortBInfo", "group___u_s_b_d_m___group.html#ga3a7dc737776ddb0cc3cb08881395cf5d", null ],
    [ "PORTC_IRQS_AR", "group___u_s_b_d_m___group.html#ga644faba17075e5177916ab57f72cbc53", null ],
    [ "PortCInfo", "group___u_s_b_d_m___group.html#gacd13612b4f497e25af9b6d70698647d8", null ],
    [ "PORTD_IRQS_AR", "group___u_s_b_d_m___group.html#ga94284af9a05b1a4782c61c711943895d", null ],
    [ "PortDInfo", "group___u_s_b_d_m___group.html#gadbf38b069ea1a57f63988b6c2f795c77", null ],
    [ "PORTE_IRQS_AR", "group___u_s_b_d_m___group.html#gad12f4eec52aa8f0e229f4ce7eadfdf61", null ],
    [ "PortEInfo", "group___u_s_b_d_m___group.html#ga0b478b3c24bc519dfa1b2a50a8c7c167", null ]
];